### ISSUE TITLE
Lack of input validation on `type` in Per hostname Authenticated Origin Pull importing leads to infinite replacement

### ISSUE THREAD

**Issue by dhaynespls** [cloudflare/terraform-provider-cloudflare#1083]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v0.14.11
+ provider registry.terraform.io/cloudflare/cloudflare v2.18.0
+ provider registry.terraform.io/hashicorp/vault v2.15.0
```

### Affected resource(s)

cloudflare_authenticated_origin_pulls_certificate

### Terraform configuration files

```hcl
resource "cloudflare_authenticated_origin_pulls_certificate" "my_aop_certificate" {
  zone_id = "my_zone_id"
  type    = "per-hostname"

  certificate = ""
  private_key = ""

  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected output

Error: `hostname` is not a valid `type`. `type` should either be `per-hostname` or `per-zone`. 

### Actual output

In state:
```
resource "cloudflare_authenticated_origin_pulls_certificate" "my_aop_certificate" {
    id      = "my_cert_id"
    type    = "hostname"
    zone_id = "my_zone_id"

    timeouts {}
}
```

Then when running a plan on a change to that resource:
```
      ~ type          = "hostname" -> "per-hostname" # forces replacement
```

### Steps to reproduce

1. terraform import cloudflare_authenticated_origin_pulls_certificate.my_aop_certificate <zone>/hostname/<id>
2. terraform plan

plan shows the following:

```
 ~ type          = "hostname" -> "per-hostname" # forces replacement
 ```

### Additional factoids

This is a simple check which should be added here: https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_authenticated_origin_pulls_certificate.go#L211

I'll create the PR shortly.

**Comment by dhaynespls** [comment]
Basically when doing an import the resource should check that you're using one of the two valid `type`s and not an arbitrary string which can mess with state because plans will expect one of the two valid `type`s.

**Comment by jacobbednarz** [comment]
Thanks for raising this @dhaynespls. At first glance, this looks like a bug however it's a little more nuanced once you dive into it. The plain english translation of `Import` is to receive an identifier, fetch the remote API based on that identifier and pull it into the state as per the `Read` instructions. In this case, the schema also states that should the local and remote resources differ, force a replacement. This is where it looks like a bug however it's actually working as designed because the end user has provided a different value to what Terraform has and Terraform has been instructed to replace the resource when that happens.

I can definitely see the benefit of having someway of validating the incoming resource against the schema however I don't quite see a sustainable way forward as we would want this for all resources; not just a single field on a single resource. I'm reaching out to some other provider maintainers and the Terraform core folks to see if there is something existing we can leverage instead. In the meantime, I'm leaning towards putting this on hold to scope out the next steps and establish a pattern for this. WDYT?

**Comment by jacobbednarz** [comment]
Unfortunately, there doesn't seem to be a great way of doing this. A more sustainable approach is to call `resourceCloudflareAuthenticatedOriginPullsCertificate().Schema["type"].ValidateFunc(aopType, "type")` which will reuse the schema validation however validating in the `Import` itself doesn't seem to be something that is widely adopted. Was there a particular driver for this one? Could something like `terraform validate` before importing help?

**Comment by dhaynespls** [comment]
@jacobbednarz There wasn't a particular driver here other than an instance of us making a typo and wanting to ensure that it didn't happen for others. That said, I do believe that running `terraform validate` probably would have caught this so that's something that we'll need to remember to do going forward when importing. I'll close this out!
