### ISSUE TITLE
`cloudflare_record` 3.0.0 Error on Plan

### ISSUE THREAD

**Issue by koalalorenzo** [cloudflare/terraform-provider-cloudflare#1208]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.5
Cloudflare 3.0.0
Atlantis v0.17.2

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "api" {
  name    = "api"
  proxied = true
  ttl     = 1
  type    = "A"
  value   = google_compute_global_address.loadbalancer_production.address
  zone_id = data.cloudflare_zones.main.zones[0].id
}
```

### Debug output

Can't replicate in Atlantis easily

### Expected output

We would expect it to plan with no changes

### Actual output

Error: missing expected [

  with cloudflare_record.api,
  on economic_application.tf line 227, in resource "cloudflare_record" "api":
 227: resource "cloudflare_record" "api" {

### Steps to reproduce

Plan

**Comment by jacobbednarz** [comment]
I think this is related to the `cloudflare_record` data attribute moving from a map (see https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/version-3-upgrade#cloudflare_record). In the state, this value will still be a map but Terraform will be looking for the list.

This is called out in the upgrade guide as not being handled by a state migration due to the changes not being a clean one to one migration between the type. If you're not using the attribute you should be able to manually update your state file to the new expected value (or potentially remove it entirely and have the `Read` set it.

**Comment by jacobbednarz** [comment]
I might be able to look at a way of handling the schema upgrade for empty `data` attributes seeing how that should be relatively straight forward and not hit the validation issues the populated values will 🤔

**Comment by antondemidov** [comment]
Having the same issue:
```
resource "aws_route53_zone" "dns-zone" {
  name = var.dns-zone-name
}

resource "cloudflare_record" "cloudflare-ns" {
  count   = (var.cloudflare-zone-id == "" ? 0 : 4)
  zone_id = var.cloudflare-zone-id
  name    = var.dns-zone-name
  value   = element(aws_route53_zone.dns-zone.name_servers, count.index)
  type    = "NS"
  ttl     = var.ttl
}
```
terraform plan:
```
│ Error: missing expected [
│
│   with module.dns-zone.cloudflare_record.cloudflare-ns[3],
│   on ../../modules/dns-zone/main.tf line 19, in resource "cloudflare_record" "cloudflare-ns":
│   19: resource "cloudflare_record" "cloudflare-ns" {
│
╵
╷
│ Error: missing expected [
│
│   with module.dns-zone.cloudflare_record.cloudflare-ns[0],
│   on ../../modules/dns-zone/main.tf line 19, in resource "cloudflare_record" "cloudflare-ns":
│   19: resource "cloudflare_record" "cloudflare-ns" {
│
╵
╷
│ Error: missing expected [
│
│   with module.dns-zone.cloudflare_record.cloudflare-ns[2],
│   on ../../modules/dns-zone/main.tf line 19, in resource "cloudflare_record" "cloudflare-ns":
│   19: resource "cloudflare_record" "cloudflare-ns" {
│
╵
╷
│ Error: missing expected [
│
│   with module.dns-zone.cloudflare_record.cloudflare-ns[1],
│   on ../../modules/dns-zone/main.tf line 19, in resource "cloudflare_record" "cloudflare-ns":
│   19: resource "cloudflare_record" "cloudflare-ns" {
│
╵
```

**Comment by Gerarddp** [comment]
A temporal workaround is to set the cloudflare provider version to < 3.0.0

```
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "2.27.0"
    }
  }
}
```

**Comment by serjaum** [comment]
I have the same issue! I rollback to 2.27 too

**Comment by elbuo8** [comment]
> If you're not using the attribute you should be able to manually update your state file to the new expected value (or potentially remove it entirely and have the Read set it.

Worked like a charm. Simply removing `data: {}` from attributes and running a plan worked.

**Comment by jacobbednarz** [comment]
i've released v3.0.1 with state migrators but _caveat emptor_, if the existing `TypeMap` is invalid it will fail the migration to `TypeList` and you'll need to manually resolve. this fix will only cover the happy paths.

**Comment by koalalorenzo** [comment]
@jacobbednarz do you know how to manually resolve, in case? :) what does that mean? do we have to manually modify the state file? 😅

**Comment by chickeaterbanana** [comment]
I had already migrated to `TypeList` after v3.0.1 I had to migrate the state another time manually because the `schema_version` had to be increased by one.

This comment is for other searching for the change which brokes the manually migration.
First I have migrated:
`terraform state pull > state.json # pull current state`
`cp state.json state.json.bak # create backup to fallback`
`# find all entries with type=cloudflare_record in state.json`
```
if instances[].data == {} then
    replace instances[].data with []
elif instance[].data is object # {"algorithm": ...}
   replace instances[].data with [object] # array of object
```
`# increase serial by one`
`terraform state push state.json`
`terraform plan # check if everything works as expected`
After v3.0.1 / 3.1.0
`# find all entries with type=cloudflare_record in state.json`
`# replace schema_version=1 with schema_version=2`
`# increase serial by one`
`terraform state push state.json`
