### ISSUE TITLE
`cloudflare_argo_tunnel` import does not include secrets

### ISSUE THREAD

**Issue by tjstansell** [cloudflare/terraform-provider-cloudflare#1439]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.8.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected resource(s)

* cloudflare_argo_tunnel

### Terraform configuration files

```hcl
resource "cloudflare_argo_tunnel" "this" {
  account_id = var.account_id
  name       = var.name
  secret     = random_id.tunnel_secret.b64_std
}
```

### Debug output

The plan output after an import of a tunnel:
```
  # cloudflare_argo_tunnel.this must be replaced
-/+ resource "cloudflare_argo_tunnel" "this" {
      ~ cname      = "<REDACTED>.cfargotunnel.com" -> (known after apply)
      ~ id         = "<REDACTED>" -> (known after apply)
        name       = "my-tunnel.example.com"
      + secret     = (sensitive value) # forces replacement
        # (1 unchanged attribute hidden)
    }
```

### Expected output

When importing a `cloudflare_argo_tunnel` resource, the secret is not available by directly querying the apis.  This means that while the basic tunnel resource is imported, the secret is not and so any plan will see a change in the secret and will then want to replace the tunnel.  The import should be updated to allow specifying the secret to import as well.

### Actual output

after import, a plan shows the secret will change and it will want to replace the tunnel.

### Steps to reproduce

1. import a `cloudflare_argo_tunnel` resource
2. plan will show the secret needs updating and want to replace the tunnel

**Comment by jacobbednarz** [comment]
the inability to include the secret is intentional behaviour because, as you mentioned, the secret is only available after creation. we don't accept passing in the secret during `Import` either because there is no way to validate that the secret you are providing matches what the service has; whatever value you end up storing there has no bearing and in some cases, will end up confusing end users if it is incorrect.

realistically, `Import` doesn't really make sense for this resource and i'd be more inclined to remove that and just recommend recreation of the resource instead.

**Comment by tjstansell** [comment]
Well, I patched the provider to allow me to import with `{accountid}/{tunnelid}/{password}` and that works great.  at least i can import an existing tunnel into terraform without having to recreate.

**Comment by jacobbednarz** [comment]
don't get me wrong, it's technically possible but you've got no way of validating it is correct. resource references are also in the same boat.

**Comment by tjstansell** [comment]
I guess I don't see the harm in letting someone import a resource with a password ... if they're managing it with terraform, they're likely referencing something like a `random_id` resource anyway... which can also get imported.  They'd just want to make sure all the pieces are consistent.  Whether the terraform provider can verify the password is correct or not seems orthogonal.  Just add a disclaimer to the import notes stating as much (_the password is only used at resource creation and cannot be changed or verified, etc, etc_).  But removing the option of importing entirely doesn't seem very friendly to the community.

**Comment by jacobbednarz** [comment]
once https://github.com/cloudflare/cloudflare-go/pull/866 lands here, we can use the get tunnel token endpoint to achieve this correctly.

**Comment by tjstansell** [comment]
I don't see how this is addressed by the linked PR. That just adds support for the tunnel token piece. You're still required to provide a secret value to the resource and if you can't import an existing secret, terraform will want to replace the resource. Import is still broken afaict.

**Comment by jacobbednarz** [comment]
as the linked PR mentions, this isn't supported for older tunnels so instead of allowing potentially incorrect `secret` value, we're setting it to empty. if you'd like to automatically handle the secret being populated, you should migrate to the newer tunnels.

you're welcome to manually populate this in your state file if you wish to use it on older tunnels however, it's not something we'll be supporting in the provider due to the risk of populating an incorrect value and having no way of verifying the correctness of the value.
