### ISSUE TITLE
cloudflare_notification_policy: "missing expected [" error

### ISSUE THREAD

**Issue by merykozlowska** [cloudflare/terraform-provider-cloudflare#1551]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.11.0

### Affected resource(s)

cloudflare_notification_policy

### Terraform configuration files

```hcl
resource "cloudflare_notification_policy" "access_service_token" {
  account_id  = "ACCOUNT_ID"
  name        = "Policy for expiring Access Service Tokens notifications"
  enabled     = true
  alert_type  = "expiring_service_token_alert"

  email_integration {
    id = "email@example.com"
  }
}
```

### Debug output

[debug.log](https://github.com/cloudflare/terraform-provider-cloudflare/files/8443525/debug.log)

### Expected output

No error and no changes to the resource.

### Actual output

```
│ Error: missing expected [
│ 
│   with cloudflare_notification_policy.access_service_token,
│   on main.tf line 12, in resource "cloudflare_notification_policy" "access_service_token":
│   12: resource "cloudflare_notification_policy" "access_service_token" {
│ 
```

### Steps to reproduce

1. Create a notification policy using Cloudflare Terraform provider version <= 3.11 (or import an existing one).
2. Update the provider to 3.12.0
3. Run `terraform plan`

### Additional factoids

I suspect this is related to the change in the schema for `filters` in this PR: https://github.com/cloudflare/terraform-provider-cloudflare/pull/1542 and the new schema is not backwards compatible with what was saved in the terraform state by the previous version of the provider (`[]` vs `{}`).

**Comment by jacobbednarz** [comment]
thanks for the issue! this is in fact due to the schema change in 3.12.0 however, there wasn't a migration included as the previous version was busted and there is no clean upgrade path, sorry for that!

in your case, there are two options forward. 1) recreate the resource which will use the correct schema going forward or 2) dive into your state file and manually swap `"filters":[]` to `"filters":{}`.

**Comment by merykozlowska** [comment]
Hi @jacobbednarz, thank you for the reply. I thought that might be the solution, and while these options are not ideal - they might be acceptable in this case (for this resource). 
However, I'd like to express a concern that this was effectively a breaking change released in a minor version and mentioned in the release notes just as a bug fix. It would be great if going forward any breaking changes were well documented and released only in major versions 🙏

**Comment by jacobbednarz** [comment]
thanks for the feedback @merykozlowska. this was noted as a minor due to the understanding this resource was broken across the board and the resource had previously been unusable for anyone that had tried to use it irrespective of the filters map was used; both good and bad to know it was actually usable at some point! 

I'll have to go back through my notes and see if there are details we overlooked here. thanks again!
