### ISSUE TITLE
Correct the documentation for cloudflare_logpush_job (Resource)

### ISSUE THREAD

**Issue by raffimohammed** [cloudflare/terraform-provider-cloudflare#1699]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Cloudflare version 3.17.0

### Affected resource(s)

N/A 

### Terraform configuration files

```hcl
N/A
```

### Debug output

N/A 

### Expected output

N/A

### Actual output

N/A 

### Steps to reproduce

N/A 

### Additional factoids

Correct this documentation: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job#dataset

**Comment by Eviradnus** [comment]
The issue is still there.

Additional details to handle this: the [`dataset` field description](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job#dataset) is copy-pasted from [its brother field `destination_conf`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job#destination_conf), which is wrong.
An appropriate description should replace said `dataset` field description.

Best regards
