### ISSUE TITLE
cloudflare_record: ignore_changes warning

### ISSUE THREAD

**Issue by gtirloni** [cloudflare/terraform-provider-cloudflare#1916]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform 1.2.9
Cloudflare provider 3.23.0

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "record" {
  zone_id  = 
  name     = 
  type     = 
  value    = 
  proxied  = 
  priority = 

  lifecycle {
    ignore_changes = [
      metadata,
    ]
  }
}
```

### Link to debug output

N/A

### Expected output

No warning

### Actual output

╷
│ Warning: Redundant ignore_changes element
│ 
│   on ../../modules/cloudflare_record/main.tf line 14, in resource "cloudflare_record" "record":
│   14: resource "cloudflare_record" "record" {
│ 
│ Adding an attribute name to ignore_changes tells Terraform to ignore future changes to the argument in configuration after the object has been created, retaining the value originally configured.
│ 
│ The attribute metadata is decided by the provider alone and therefore there can be no configured value to compare with. Including this attribute in ignore_changes has no effect. Remove the attribute from ignore_changes to quiet this
│ warning.
│ 
│ (and 5 more similar warnings elsewhere)

### Steps to reproduce

1. terraform plan

### Additional factoids

Warning started to appear after upgrading to terraform 1.2.x

### References

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2081

**Comment by gtirloni** [comment]
More context: we needed to ignore this attribute because an external tool we use makes changes to the records metadata and `terraform plan` was always showing changes that impacted our ability to do configuration drift detection. Now with terraform 1.2, it seems these changes are ignored automatically (if we didn't define any metadata in terraform code itself). We still have other environments in various terraform versions, and they are sharing this module, so we wanted to come up with a solution that would work across all versions... it's become a bit confusing now and I'd appreciate if you could shed some light on this issue.

Does this all mean that, starting with terraform 1.2, we wouldn't need to explicitly ignore metadata in this situation?

**Comment by jacobbednarz** [comment]
your example and lack of debug output doesn't really provide me with any information that points to this being an issue on the provider side. as such, this is most likely something you'll need to chat with the Terraform core team about since it's not a change we've made here.

**Comment by apparentlymart** [comment]
Hello! I'm a member of the Terraform Core team.

We later discussed this in [the Terraform community forum](https://discuss.hashicorp.com/t/ignore-changes-warning/44572) but I just wanted to push some context back here in case it's useful for future discussion:

The `ignore_changes` feature tells Terraform to ignore any differences between the configuration of a resource instance and a pre-existing object associated with that resource instance. Specifically, Terraform will replace whatever is in written in the configuration with whatever value is stored in the prior state before it asks the provider to plan changes to the object.

This option therefore does nothing at all for an attributes which cannot be set in the configuration, which in the SDK means that `Computed: true` is set without also setting `Optional: true`.

The Terraform Core team observed that many authors were trying to use `ignore_changes` with such attributes and being confused that it was effectively totally ignored without any feedback, and so this warning is an attempt to make it explicit that including a computed-only attribute in `ignore_changes` is (and always has been) completely ineffective.

With that said then: the only behavior change here is that Terraform now returns a warning rather than just silently ignoring the redundant entry. No provider change is needed here, and instead the solution is to (as the warning message mentions) remove the redundant entry from `ignore_changes`.

The more context above implies that this was doing something useful in earlier versions of Terraform, but I am not aware of any way that could be true: prior versions of Terraform would still have had no configuration for `metadata` to compare with, and so would _always_ use the value stored in the prior state because that's the only value actually available for that attribute. Removing the `ignore_changes` setting should therefore make no difference to Terraform v1.1's behavior either. If you do see earlier versions of Terraform behaving differently without this `ignore_changes` setting then we'd love to hear more about that, though to avoid disturbing the maintainers of this provider any further we'll continue discussing this over in the community forum topic. Thanks!

**Comment by jacobbednarz** [comment]
thanks for the details @apparentlymart! appreciate it!
