### ISSUE TITLE
Duplicate data source docs

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/terraform-provider-cloudflare#1927]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Latest

### Affected resource(s)

Docs

### Expected output

Single data source file for each data source.

### Actual output

It appears that the data source docs are duplicated for each resource, (except for `record.md`).
In the [docs directory](https://github.com/cloudflare/terraform-provider-cloudflare/tree/master/docs/data-sources), each appears as `x.md` and `cloudflare_x.md`. It seems a mix of what is up-to-date. The data sources with `cloudflare_*.md` were last generated 4 months ago, but they contain the examples, whereas the `x.md` were mostly generated 16 days ago but contain just the raw attributes.

**Comment by jacobbednarz** [comment]
good spot. this happens because the generation process takes everything in `templates/*`, copies it over verbatim into the docs and then generates the schemas using the remaining resources. the issue here is that some of the filenames were prefixed with `cloudflare_` whereas the template generation looks for only the resource name minus the provider resulting in duplication. i'll push up a PR shortly addressing this.
