### ISSUE TITLE
cloudflare_worker_script is unable to upgrade to 4.x due to account_id

### ISSUE THREAD

**Issue by JDKnobloch** [cloudflare/terraform-provider-cloudflare#2286]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

1.3.1 TF
4.1.0 CF Provider
(note this issue is already [marked closed & complete](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2221) under issues, another community member as well as myself have both notified the maintainer in that thread but due to lack of response I am opening this new issue)

### Affected resource(s)

cloudflare_worker_script

### Terraform configuration files

```hcl
resource "cloudflare_worker_script" "dis_dont_work" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "script_1"
  content    = file("script.js")
}
```

### Link to debug output

N/A

### Expected output

Plan / apply successfully 

### Actual output

```
│ Error: Error reading worker script from API for resource &{ZoneID: ScriptName:dis_dont_work}: required missing account ID
│ 
│   with cloudflare_worker_script.dis_dont_work,
│   on somefile.tf line 12, in resource "cloudflare_worker_script" "dis_dont_work":
│  12: resource "cloudflare_worker_script" "dis_dont_work" {
│ 
```

### Steps to reproduce

1. Attempt to use resource as documented
2. It does not work as documented / at all on the latest version
    a. (Optional) Ponder 🤔 about baseline functionality tests for resources (would definitely help on these large deprecations)
3. Open issue on the CF TF provider (recursive 😄)

### Additional factoids

With 4.x update there was no consideration for upgrade paths regarding renamed resources. Unrelated to this issue, but resources were renamed directly with no schema staged / available as an upgrade path.

For example - `cloudflare_argo_tunnel` was renamed `cloudflare_tunnel`. On 3.9.x, only `cloudflare_argo_tunnel` exists. On 4.x, only `cloudflare_tunnel`. This means there is no version of the provider that allows `terraform state mv` to be executed to move resources in place, as schema is not available for both simultaneously. Importing into the new resource name was not viable (for us) due to generated random_id secrets passed in whose values cannot be imported with the resource - full manual intervention within state file JSON was required to move these resources without forcing recreation (i.e. forcing down time as tunnel locations move). 

Similar issue exists on `cloudflare_ip_list` rename to `cloudflare_list,` though in this case we were able to import and rm the former resources from state. This is not ideal, even if it works.

In the future, having matching schema on two resources for at LEAST a single version allows an easy upgrade path - or any upgrade path at all, frankly. If both `cloudflare_argo_tunnel` & `cloudflare_tunnel` both existed on registry for a single version, `terraform state mv` could be used  as schema is available for both of them, and a considerable headache could be saved for users.

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/worker_script
I initially pinged regarding on the [original issue for this resource](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2221)

**Comment by jacobbednarz** [comment]
> Attempt to use resource as documented
> It does not work as documented / at all on the latest version
> a. (Optional) Ponder 🤔 about baseline functionality tests for resources (would definitely help on these large deprecations)

we are already doing automated validation of resources through acceptance tests. you can see and run the acceptance tests in https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/resource_cloudflare_workers_script_test.go. the documentation on the registry is a trimmed down version of the acceptance tests and works for me here when all attributes are provided.

if you're still seeing issues, please open an issue with all the requested information including a TF_LOG=DEBUG log.

> (note this issue is already [marked closed & complete](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2221) under issues, another community member as well as myself have both notified the maintainer in that thread but due to lack of response I am opening this new issue)

if you are seeing issues with functionality after an issue is closed as completed, you should open a new issue providing all the requested information from the issue template. this ensures your exact issue is triaged for your scenario. the issue you have linked was addressed as working as expected since it was during a swap over period that both `account_id`s needed to be provided while we removed it from some resources and not others.

> With 4.x update there was no consideration for upgrade paths regarding renamed resources. Unrelated to this issue, but resources were renamed directly with no schema staged / available as an upgrade path.

the `cloudflare_argo_tunnel`/`cloudflare_tunnel` move was my bad and not intentional, thanks for the feedback. however, `cloudflare_ip_list` and `cloudflare_list` were intentional as they are not 1:1 resources and people shouldn't be blindly moved between even if the types matched up.

**Comment by JDKnobloch** [comment]
Awesome - thanks for getting back, happy to know about the acceptance tests 😄👍 

Appears the issue is specifically stemming from the fact our resource is not net new and already exists in state w/o account_id. I ran some debug logs, but the state we have this resource in is large, leading to convoluted logs I did not want to dig through 😅 - I instead quickly tested a net new `cloudflare_worker_script` resource / state and confirmed the plan ran without issue.

Once confirmed, I manually edited our tfstate file and filled the account_id variable (prior it was in state as `account_id = null`). I would have liked to try iterating through versions to see if that field filled out at some point, but this specific state contained other renamed resources that I manually changed during this version bump and it would have been a headache to fully return to the old state / provider version.

So suffice to say - the resource / acceptance tests worked correctly, but in our scenario where the resource already exists w/o account_id variable / field existing and it then being added during upgrade, this issue occurred. Seems like it may be a race condition.

I'll leave it to you to if you would like to close this issue or not 🤷 I believe others will likely hit this as they upgrade, but they should also be able to mitigate in the same way we were able to. Lmk if you would like any other info from me.

**Comment by jacobbednarz** [comment]
> So suffice to say - the resource / acceptance tests worked correctly, but in our scenario where the resource already exists w/o account_id variable / field existing and it then being added during upgrade

unfortunately we don't have test coverage for every edge case possible with stored state; there are just far too many variables for us to take into account so we focus on the expected paths. however, in the case of the deprecation/move, it was something we ran internally for at least a month before it landed in the public repository and i didn't have any reports of existing resources not being successfully upgraded so it feels like something else contributed here.

> Seems like it may be a race condition.

the only case in which this should have been was if you went from an older version without the bridging code to a new version where the bridge is removed (4.x) and the `account_id` was never saved as the newer value. it would made things worse again if you stuck with `account_id` at the provider config until 4.x since you would have missed the bridging code completely.

if this is the case, i'm not going to worry about leaving this open as the bridging code and deprecation notice should have been the upgrade path that most people took and there is a simple work around if people do get into this state (`terraform state rm ...` and `terraform import ...`).

thanks for the issue and i'm glad we got it sorted!

**Comment by JDKnobloch** [comment]
Yup, no worries; figured incremental upgrading would have solved it, this resource was one of the few leftovers from our initial wave of `account_id` migrations and just ended up being missed. 

Thanks for the insights!

**Comment by AaronShiels** [comment]
I'm also performing a large version jump on the Cloudflare provider and believe I've hit the same issue.

Could we perhaps state the last version that contained the bridging code, for completion's sake? We use Atlantis to centralise our Terraform deployments, so direct manipulation with `terraform rm/import` is a little more difficult, and the intermediary deployment might be more palatable to some.
