### ISSUE TITLE
cloudflare_access_group documentation is not clear for azure

### ISSUE THREAD

**Issue by userbradley** [cloudflare/terraform-provider-cloudflare#2299]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
➜ terraform -v            
Terraform v1.4.2
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.1.0

```

### Affected resource(s)

`cloudflare_access_group`

![image](https://user-images.githubusercontent.com/41597815/225952900-9d967a83-a849-46c6-9d7f-30f07cf33b28.png)

### Terraform configuration files

```hcl

resource "cloudflare_access_group" "g_test" {
  name = "g_test"
  zone_id = "<redacted>"
  include {
    azure {
      identity_provider_id = "<redacted>"
      id = ["<redacted>"]
    }
  }
}
```

### Link to debug output

na

### Expected output

The documentation states that under `include.azure` the field `id` is **read only** when it is in fact not

### Actual output

The documentation should read more like

**Nested Schema for [`include.azure`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_group#nested-schema-for-includeazure)**

### Required

* [`identity_provider_id`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_group#identity_provider_id) (string) - The ID of the Azure Identity provider
* [id](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_group#id) (List of String) The ID of the Azure group or user.

### Steps to reproduce

Look at documentation https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_group#nestedblock--include--azure

### Additional factoids

The provider documentation lacks examples for all the options it has.

Would be worth while adding in an example for the azure group like:

``` tf
resource "cloudflare_access_group" "g_test" {
  name = "g_test"
  zone_id = "<redacted>"
  include {
    azure {
      identity_provider_id = "<redacted>"
      id = ["<redacted>"]
    }
  }
}
```

**Comment by jacobbednarz** [comment]
this is an artifact of the tool we use to generate the registry documentation. where `id` is present and does not include a schema description, it is assumed read only - https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/schema_cloudflare_access_group.go#L180-L186.

if you'd like to submit a PR addressing this, please check out https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md on how to update the documentation. otherwise, i'll drop this into the teams internal backlog for it to be prioritised.
