### ISSUE TITLE
Improve cloudflare_teams_rule documentation

### ISSUE THREAD

**Issue by Qbandev** [cloudflare/terraform-provider-cloudflare#2478]
### Current Terraform and Cloudflare provider version

version = "4.6.0"

### Description

The Terraform module  [teams_rule](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/teams_rule) documentation should be improved because there is no mention of Zero Trust.

I found the response in this issue thread #2259

### Use cases

Improve the documentation to make it easier to implement Zero Trust Gateway:  Network Firewall Policy

### Potential Terraform configuration

```hcl
...
```

### References

#2259

**Comment by jacobbednarz** [comment]
can you please be specific about what you're intended outcome is here? a general "improve docs" issue here does not help identify what you explicitly want to see differently here.

**Comment by Qbandev** [comment]
Hi @jacobbednarz 

In the Terraform provider [teams_rule](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/resources/teams_rule.md?plain=1) readme there is no mention that can be used to configure Cloudflare Zero Trust like [DNS Policies](https://developers.cloudflare.com/cloudflare-one/policies/filtering/dns-policies/) and uses this [API](https://developers.cloudflare.com/api/operations/zero-trust-gateway-rules-create-zero-trust-gateway-rule) endpoint. 

```markdown
# cloudflare_teams_rule (Resource)

Provides a Cloudflare Teams rule resource. Teams rules comprise secure web gateway policies.
```


Also, it should be nice to provide another example to configure Zero Trust DNS policies like:

```hcl
resource "cloudflare_teams_rule" "zero_trust_dns_policies" {
  enabled     = true
  name        = "Cloudflare Zero Trust - Secure Web Gateway - DNS Policies - Block"
  account_id  = cloudflare_account_id
  description = "DNS filter to block the topics: “malware”, “phishing”, “spam”, “spyware”."
  precedence  = 100
  action      = "block"
  filters     = ["dns"]
  traffic     = "any(dns.security_category[*] in {117 131 151 153})"
  identity    = "any(identity.groups.name[*] in {\"employees\"})"

  rule_settings {
    block_page_enabled = true
    block_page_reason  = "Access not permitted by DNS Policy"
  }
}
```

Is a bit confusing get `team_rules` == [Cloudflare Zero Trust --> Secure Web Gateway --> DNS Policies](https://developers.cloudflare.com/cloudflare-one/policies/filtering/dns-policies/) as already pointed [here](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2259#issuecomment-1447119307) in the #2259

**Comment by jacobbednarz** [comment]
to answer the question here, yes, the product used to be called teams before zero trust/gateway and the resource has not been renamed due to it being a breaking change. perhaps on the next major release we can look at a unification of these terms. 

as for the terraform examples, we intentionally don't provide kitchen sink style examples of every possible combination. instead we document what the resource provides and any schema details associated with it. the developer docs are generally the place for more detailed examples so you're welcome to open an issue in `cloudflare/cloudflare-docs` if you want a more canonical source of how these various configurations could work in your setup. 

if you'd like to see some specific changes to the terraform documentation, feel free to take a look at https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md for how to propose changes and we can review it.
