### ISSUE TITLE
Inconsistent state when setting multiple cloudflare_list_item

### ISSUE THREAD

**Issue by bunnybilou** [cloudflare/terraform-provider-cloudflare#2559]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.9.0
+ provider registry.terraform.io/datadog/datadog v3.26.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/http v3.4.0

### Affected resource(s)

- cloudflare_list_item

### Terraform configuration files

```hcl
resource "cloudflare_list" "cloudflare" {
  account_id  = var.account_id
  name        = "cloudflare"
  description = "cloudflare public IPs"
  kind        = "ip"
}

resource "cloudflare_list_item" "cloudflare1" {
  account_id = var.account_id
  list_id    = cloudflare_list.cloudflare.id
  ip         = "1.1.1.1"
}

resource "cloudflare_list_item" "cloudflare2" {
  account_id = var.account_id
  list_id    = cloudflare_list.cloudflare.id
  ip         = "1.1.1.2"
}

resource "cloudflare_list_item" "cloudflare3" {
  account_id = var.account_id
  list_id    = cloudflare_list.cloudflare.id
  ip         = "1.1.1.3"
}
```

### Link to debug output

https://gist.github.com/bunnybilou/1b6307b5eefc694cd07dd2cab25e502b

### Expected output

Subsequent plans and applys should not contain any modifications.

### Actual output

When I add multiple `cloudflare_list_item` to a `cloudflare_list` simultaneously, the initial apply goes smoothly. All the resources are created correctly. However, subsequent plans or applys contain modifications.

### Steps to reproduce

1. create a `cloudflare_list` with multiple `cloudflare_list_item` with terraform apply.
2. rerun `terraform apply` or `terraform plan` and you will get diff.

### Additional factoids

What I saw in the state is that all the `cloudflare_list_item` ressources are sharing the same id and this is why next plan / apply is containing diffs.

it's clearly visible in the first apply that something is wrong with the ids (same value for the 3 ressources)

```
cloudflare_list.cloudflare: Creating...
cloudflare_list.cloudflare: Creation complete after 2s [id=7c521cc1bcd84fe0ad70a3ac04d7fe0b]
cloudflare_list_item.cloudflare3: Creating...
cloudflare_list_item.cloudflare1: Creating...
cloudflare_list_item.cloudflare2: Creating...
cloudflare_list_item.cloudflare3: Creation complete after 4s [id=1f5fa85234e04c69b1721050874f6a01]
cloudflare_list_item.cloudflare2: Creation complete after 4s [id=1f5fa85234e04c69b1721050874f6a01]
cloudflare_list_item.cloudflare1: Creation complete after 5s [id=1f5fa85234e04c69b1721050874f6a01]
```

**Comment by jacobbednarz** [comment]
putting this one on hold as there seems to be an issue with fetching individual records from a bulk operation ID that we'll need to solve internally first.

**Comment by danquack** [comment]
I noticed when I imported vs creating the list item, the plan seemed to stay consistent across executions. But when creating the list item, the ids were being stored as the same. 

In the following block, you're capturing the state id from the most recently created item. https://github.com/cloudflare/terraform-provider-cloudflare/blob/ce0d1b590391328c33f9cee0e669b4e72c7c3ca0/internal/sdkv2provider/resource_cloudflare_list_item.go#L58-L59

What I noticed in my state file, is the ids were being stored as the same:
```
# cloudflare_list_item.nat_egress_ip["1.1.1.2"]:
resource "cloudflare_list_item" "nat_egress_ip" {
    account_id = (sensitive value)
    comment    = "Cluster Egress IP"
    id         = "<redacted>bb"
    ip         = "54.221.169.86"
    list_id    = "<redacted>"
}

# cloudflare_list_item.nat_egress_ip["1.1.1.1"]:
resource "cloudflare_list_item" "nat_egress_ip" {
    account_id = (sensitive value)
    comment    = "Cluster Egress IP"
    id         = "<redacted>bb"
    ip         = "1.1.1.1"
    list_id    = "<redacted>"
}
```

Instead of slicing by latest createdAt timestamp, could you match to something the user provides, such as the required field of the itemType? I could put forward a PR, but figure it might be better to have a conversation first from the design perspective.

**Comment by danquack** [comment]
I noticed when I imported vs creating the list item, the plan seemed to stay consistent across executions. But when creating the list item, the ids were being stored as the same. 

In the following block, you're capturing the state id from the most recently created item. https://github.com/cloudflare/terraform-provider-cloudflare/blob/ce0d1b590391328c33f9cee0e669b4e72c7c3ca0/internal/sdkv2provider/resource_cloudflare_list_item.go#L58-L59

What I noticed in my state file, is the ids were being stored as the same:
```
# cloudflare_list_item.nat_egress_ip["1.1.1.2"]:
resource "cloudflare_list_item" "nat_egress_ip" {
    account_id = (sensitive value)
    comment    = "Cluster Egress IP"
    id         = "<redacted>bb"
    ip         = "1.1.1.2"
    list_id    = "<redacted>"
}

# cloudflare_list_item.nat_egress_ip["1.1.1.1"]:
resource "cloudflare_list_item" "nat_egress_ip" {
    account_id = (sensitive value)
    comment    = "Cluster Egress IP"
    id         = "<redacted>bb"
    ip         = "1.1.1.1"
    list_id    = "<redacted>"
}
```

Instead of slicing by latest createdAt timestamp, could you match to something the user provides, such as the required field of the itemType? I could put forward a PR, but figure it might be better to have a conversation first from the design perspective.

**Comment by ddesboroughv** [comment]
I can verify what @danquack wrote about things working and staying stable after importing. It is simply the initial creation that fails to properly capture the correct ID when there is a bulk create. For now, I am reduced to making singular additions to the IP list we are maintaining via terraform. I am so glad I found this because I really thought I was doing something incorrect for a while.

**Comment by ddesboroughv** [comment]
For clarification, this could impact IP, ASN, HOSTNAME, and REDIRECT lists as the same code handles all four list types.

**Comment by AndrewUnderwoodAtFanatics** [comment]
This is affecting us as well, it's caused some pain in our provisioning process.  The `import` mitigation does work for us but it's still pretty painful considering the rate at which we use this resources.  Is there any update on when this might be resolved?
