### ISSUE TITLE
Example Documentation for GRE and IPsec has the same IP for customer and cloudflare endpoints

### ISSUE THREAD

**Issue by jeffsani** [cloudflare/terraform-provider-cloudflare#2575]
### Current Terraform and Cloudflare provider version

Any

### Description

The Cloudflare Endpoint IP and Customer Endpoint IP should be discrete in the examples provided.  Suggest these also reference the reserved prefixes in RFC 5737 used for documentation:

[](https://datatracker.ietf.org/doc/html/rfc5737)

### Use cases

Any customer wanting to use this for automation of Magic WAN or Magic Transit

### Potential Terraform configuration

N/A

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/gre_tunnel

**Comment by jacobbednarz** [comment]
> Suggest these also reference the reserved prefixes in RFC 5737 used for documentation:

the IPs in our documentation already use rfc5737 and rfc3849 (203.0.113.1 is within 203.0.113.0/24).

feel free to send over a PR based on https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md if you'd like to see this updated otherwise i'll put it into the team's back log and they will triage it.
