### ISSUE TITLE
Missing upgrade path for `cloudflare_argo_tunnel` resource.

### ISSUE THREAD

**Issue by AllexVeldman** [cloudflare/terraform-provider-cloudflare#2598]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Upgrade v3.35.0 to any v4 version.

### Affected resource(s)

- `cloudflare_argo_tunnel`
- `cloudflare_tunnel`

### Terraform configuration files

```hcl
# Before
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "3.35.0"
    }
  }
}

resource "cloudflare_argo_tunnel" "argo-tunnel" {
  name       = "tunnel_name"
  account_id = "accountID"
  secret     = "secret"
}

# After
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "4.9.0"
    }
  }
}

resource "cloudflare_tunnel" "argo-tunnel" {
  name       = "tunnel_name"
  account_id = "accountID"
  secret     = "secret"
}
```

### Link to debug output

na

### Expected output

A minor version of the provider that contains both `cloudflare_argo_tunnel` and `cloudflare_tunnel` resources so we have an upgrade path for the tunnel before removing `cloudflare_argo_tunnel`.

### Actual output

```
╷
│ Warning: Missing resource schema from provider
│ 
│ No resource schema found for cloudflare_argo_tunnel when decoding prior
│ state
╵
╷
│ Error: no schema available for module.cf-argo-tunnel.cloudflare_argo_tunnel.argo-tunnel while reading state; this is a bug in Terraform and should be reported
│ 
│ 
╵
```

### Steps to reproduce

1. Create a `coudflare_argo_tunnel` resource on v3
2. Update the provider to v4
3. change `cloudflare_argo_tunnel` to `cloudflare_tunnel`

### References

- https://github.com/cloudflare/terraform-provider-cloudflare/pull/2135
- https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations#provider-data-source-or-resource-rename

**Comment by jacobbednarz** [comment]
this is a known oversight in the 3.x -> 4.x migration and to resolve you can either:

1. manually update the state file with the new resource name
2. remove the resources from state, perform the upgrade and then reimport the resources back into the state. 

the way the registry release process works, non-linear and non-latest releases aren't supported without hand holding from hashicorp so we won't be releasing an older version at this time.

**Comment by christidis** [comment]
Typically if you upgrade provider remove the cloudflare_argo_tunnel and import the cloudflare_tunnel will raise a destroy and recreation operation for the tunnels which needs some more work to re-establish the connection with the tunnels and possible downtime.

I have managed to complete this update **without a recreation of the tunnels** which was a bit tricky and is not even communicated as a how-to guide in the docs or within the community (at least I didn't find much). 

Please note that in the following example, the tunnel was cloudflare managed (`config_src=cloudflare`). If your tunnel is locally managed then set this to `local` as the documentation of the `cloudflare_tunnel` suggests.

First, before the upgrade I pulled the existing state locally.
```
>terraform state pull  > /tmp/state-dev-db/state.before
```
 
Then I updated the provider version in version.tf to ~> 4.0. I also renamed `cloudflare_argo_tunnel` to `cloudflare_tunnel` in my TF code.
```
sed -i 's/cloudflare_argo_tunnel/cloudflare_tunnel/g' *.tf
```
 

I also had to delete my tunnel-config configuration from the state file (not sure why this was affecting my import)
```
>terraform state rm 'cloudflare_tunnel_config.dev_db_tunnel_configs["dev-db-tunnel-01.pubs-acs-db"]'
```
 

Then I imported the tunnel configuration with the expected resource name
```
>terraform import 'cloudflare_tunnel.dev_db_tunnels["dev-db-tunnel-01"]' 7642d9473b4a1048e670cc71ce189b41/3868f1ba-2696-4ce1-a819-b31fb1bb5203
```
 

I also had to delete the old argo resource, as the resource does not exist in the new provider
```
>terraform state rm 'cloudflare_argo_tunnel.dev_db_tunnels["dev-db-tunnel-01"]'
```
 

Then I pulled the existing state locally (again, after the import).
```
>terraform state pull  > /tmp/state-dev-db/state.after
```
 

Then I bumbed seriar number and in the `type": "cloudflare_tunnel",` section I filled in the secret and config_src settings which were `null` (I got the values from the `/tmp/state-dev-db/state.before` file). This allowed me to perform an _in-place_ update for the tunnel and not a recreation of the tunnel. Then I saved the new state as `/tmp/state-dev-db/state.after.updated` and I pushed the configuration
```
>terraform state push > /tmp/state-dev-db/state.after.updated
```
 

Finally I applied the configuration with terraform apply which performed an in-place updates to the resource but not a recreation of the tunnel (in order to set some sensitive values, ordering etc)
```
>terraform apply
```

The apply also created in the state the removed tunnel_configs and everything is set now.

Hope this helps!

**Comment by warwick-mitchell1** [comment]
We've finally had to bite the bullet with this migration and this is the one liner I've used to update our state files.

```
 bf="$(terraform workspace show)-backup.tfstate" && terraform state pull > "${bf}" && jq '.serial +=1' "${bf}" > new.tfstate && sed -i 's/cloudflare_argo_tunnel/cloudflare_tunnel/g' new.tfstate && terraform state push new.tfstate
```
