### ISSUE TITLE
Failsafe mechanism for cloudflare_ip_ranges

### ISSUE THREAD

**Issue by dacevedo12** [cloudflare/terraform-provider-cloudflare#2894]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

3.10.0

### Affected resource(s)

cloudflare_ip_ranges (cidr_blocks)

### Terraform configuration files

```hcl
data "cloudflare_ip_ranges" "cloudflare" {}

data.cloudflare_ip_ranges.cloudflare.cidr_blocks
```

### Link to debug output

n/a

### Expected output

shouldn't have returned empty in the first place. In case of cloudflare unavailability it should fail instead. 

### Actual output

it returned an empty list of cidr_blocks, without any error.

terraform proceeded to apply this leading to unavailability (403) in one of the buckets we had restricted to these specific IP ranges.

### Steps to reproduce

Likely needs more investigation on your side as we've only seen this happen during today's availability issues.

### References

https://downdetector.com/status/cloudflare/

**Comment by dacevedo12** [comment]
I wish I had more debug details but as I mentioned, this only happened during today's availability issues.

By the time I re-ran the terraform apply, it returned the correct values.

This is more of a, fail gracefully during these kind of events

**Comment by jacobbednarz** [comment]
thanks for the issue! unfortunately, this isn't something to be addressed in the provider. the issue was the service we call via the API failed open during the incident instead of returning an error (we already handle API errors with https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/data_source_ip_ranges.go#L57). that's something i can pass onto the team however, there isn't anything to do here that would have prevented it given it still returned a success.

side note: please don't rely on downdetector for anything. it's a horrible system that scrapes for "<service> down" mentions across platforms and is not an accurate measure of availability. instead, you can subscribe to individual service updates via the platform status page (such as https://www.cloudflarestatus.com/)

**Comment by dacevedo12** [comment]
It happened again. Any updates on whether the API team is working on addressing this?

This is fairly serious

**Comment by dacevedo12** [comment]
For future reference, the workaround is
```
data "cloudflare_ip_ranges" "cloudflare" {
  lifecycle {
    postcondition {
      condition     = length(self.cidr_blocks) > 0
      error_message = "CloudFlare's API returned empty list of IPs"
    }
  }
}
```
at least with that, the deployment will be stopped before it can cause any damage.
