### ISSUE TITLE
No way to enable the default `<worker_name>.<account_name>.workers.dev` route in `cloudflare_worker_script`

### ISSUE THREAD

**Issue by garysassano** [cloudflare/terraform-provider-cloudflare#3268]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform: 1.8.2
Cloudflare provider: 4.30.0

### Affected resource(s)

`cloudflare_worker_script`

### Terraform configuration files

```hcl
read below
```

### Link to debug output

read below

### Expected output

read below

### Actual output

read below

### Steps to reproduce

1. Deploy a `cloudflare_worker_script` resource

2. Go to `<worker_name>` ➜ Settings ➜ Triggers

   ![worker-routes](https://github.com/cloudflare/terraform-provider-cloudflare/assets/10464497/5189df52-996a-4441-b2ed-84c08cc90bff)

3. You see that the worker script got deployed, but the default route associated with it is disabled. There's no property in the `cloudflare_worker_script` resource which allows to specify that you want to deploy the worker with the default route enabled.

**Comment by jacobbednarz** [comment]
this is not a bug but an enhancement to a resource. please lodge this with customer support or your account team to have them escalate it to the respective service team. 

duplicate of #2892, #1921 and #1013.

**Comment by garysassano** [comment]
@jacobbednarz How is an enhancement to prevent users from correctly configuring their resources? You allow to do it in Wrangler but not in Terraform, so there's clearly something wrong.

**Comment by garysassano** [comment]
How is it an enhancement to prevent users from correctly configuring their resources? You allow to do it in Wrangler but not in Terraform, so there's clearly something wrong.

**Comment by garysassano** [comment]
It's concerning that SST had to resort to examining Wrangler's source code to discover and utilize a shadow API for [enabling the default route](https://github.com/sst/ion/blob/dev/pkg/platform/src/components/cloudflare/providers/worker-url.ts#L72). Relying on such workarounds shouldn't be necessary, and Cloudflare should provide proper documentation and official support for this basic functionality.

**Comment by jacobbednarz** [comment]
it's an enhancement because the resource works, it is however missing a particular function of the service. there is work in progress to make this automatic (see https://blog.cloudflare.com/lessons-from-building-an-automated-sdk-pipeline) but for the mean time, it is a feature request to the service team to implement. 

you can see the reasoning behind it not existing in the SDKs (and subsequently Terraform) at https://github.com/cloudflare/cloudflare-go/blob/master/docs/public-api-documentation.md#but-wranglercloudflaredother-project-doesnt-require-public-documentation. 

i totally agree there is an issue here lacking coverage but to address it, we need the service team to add the new feature which is not tracked in GitHub (until the automation is in place).
