### ISSUE TITLE
Legacy keys missing from OpenTofu's Registry

### ISSUE THREAD

**Issue by cam72cam** [cloudflare/terraform-provider-cloudflare#3366]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

OpenTofu v1.6.2 - cloudflare 2.10.0 through 3.9.1

### Affected resource(s)

All

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      version = "~> 2.21"
      source = "cloudflare/cloudflare"
    }
  }
}
```

### Link to debug output

N/A

### Expected output

Successful init

### Actual output

- Installing cloudflare/cloudflare v2.27.0...
╷
│ Error: Failed to install provider
│ 
│ Error while installing cloudflare/cloudflare v2.27.0: the provider is not signed with a valid signing key; please contact the provider author (authentication signature from unknown issuer)
╵

### Steps to reproduce

Download OpenTofu
Create config pointing at version with legacy provider key
tofu init

### References

https://github.com/opentofu/registry/issues/680

**Comment by jacobbednarz** [comment]
👋 thanks for raising this one. unfortunately, these legacy keys were created and not stored for longer term use since they were only used in the Hashicorp ecosystem and we never actually had to exercise them on our side outside of the automated pipeline.

they remain usable on the Terraform registry since we cannot delete them but aside from that, i don't think we have them. i'll have a dig around and if i manage to find them, open a PR for opentofu otherwise, it's not something we can backfill. sorry!

**Comment by jacobbednarz** [comment]
good news! i found an old email where we provided this to Hashicorp so i was able to submit it for addition to the registry via opentofu/registry#684

**Comment by cam72cam** [comment]
Thanks @jacobbednarz!
