### ISSUE TITLE
`cloudflare_tunnel` resource cannot be imported without recreating the tunnel because imported tunnels don't have the tunnel secret in state

### ISSUE THREAD

**Issue by xortive** [cloudflare/terraform-provider-cloudflare#3950]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform 1.5.5
provider 4.39.0

### Affected resource(s)

cloudflare_tunnel

### Terraform configuration files

```hcl
resource "cloudflare_tunnel" "example" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "my-tunnel"
  secret     = base64decode(jsondecode(base64decode(<base64 encoded tunnel token, as returned by the /token endpoint of the api>))["s"])
}

import {
  to = cloudflare_tunnel.my_tunnel
  id = "f037e56e89293a057740de681ac9abbe/e83a2443-e0c6-4d81-8eb0-d90f56be0375"
}
```

### Link to debug output

N/A

### Panic output

N/A

### Expected output

An imported tunnel is not recreated when the same secret is provided

### Actual output

The tunnel was recreated

### Steps to reproduce

Import any tunnel and provide the existing secret

### Additional factoids

I believe two changes are required to fix this correctly.

* pull the secret value out of the token and store that as well as the token in the state in [`resourceCloudflareTunnelRead`](https://github.com/cloudflare/terraform-provider-cloudflare/blob/e16465e49e08ddf13dd5ed8a383b4cf20ecea36d/internal/sdkv2provider/resource_cloudflare_tunnel.go#L89)
* [`secret`](https://github.com/cloudflare/terraform-provider-cloudflare/blob/v4.39.0/internal/sdkv2provider/schema_cloudflare_tunnel.go#L29) should not have `ForceNew: true` as the [API supports PATCH now](https://developers.cloudflare.com/api/operations/cloudflare-tunnel-update-a-cloudflare-tunnel)

Also, #3355 is correct that `secret` should not be a required field, but is incorrect on the reasoning why -- I will add a comment to that issue about this.

### References

#3355 documents the tunnel token format

**Comment by richjyoung** [comment]
This makes it impossible to migrate from `cloudflare_tunnel` resource types to `cloudflare_zero_trust_tunnel_cloudflared` without destroying an existing tunnel. `terraform state mv` cannot handle changing the resource type so our only option was remove the old resource type from the state and then import the new one, except the secret forces replacement.

**Comment by StanScates** [comment]
+1, as far as I can tell, there is currently **no upgrade path from v4 to v5** without destroying and re-creating`cloudflare_zero_trust_*` resources:

1. Using [moved](https://developer.hashicorp.com/terraform/language/modules/develop/refactoring#moved-block-syntax) is not an option as the provider doesn't support it - @jacobbednarz mentions [this is not supported](https://github.com/cloudflare/terraform-provider-cloudflare/issues/3899#issuecomment-2330211319) in the SDKv2 framework (which I am assuming is the reason the provider does not / can not support it).
2. Renaming resources via `terraform state mv` is not supported:
```
│ Error: Invalid state move request
│
│ Cannot move cloudflare_tunnel.internal-tunnel to cloudflare_zero_trust_tunnel_cloudflared.internal-tunnel: resource types don't match.
```
3. Finally, removing the resources from state and re-importing them is not supported due to this issue.

The official migration guidance appears to suggest renaming the resources should be sufficient (which will destroy and re-create the resources), however this doesn't work as many of the resources will not allow destruction while associated with other resources, requiring methodical manual teardown of all associated resources (and incurring significant downtime).

There have already been quite a number of complaints around these issues and I suspect as time goes on there will only be more. For now we are stuck on 4.x.

@jacobbednarz can you please weigh in? I've chosen to leave this as a comment instead of creating a new issue, but I sincerely believe this situation will result in many new issues filed in the coming months (I have already found ~10).
