### ISSUE TITLE
Add support for all Authenticated Origin Pull APIs

### ISSUE THREAD

**Issue by dhaynespls** [cloudflare/terraform-provider-cloudflare#736]
hello!

Building off of the work done in https://github.com/cloudflare/cloudflare-go/issues/498 I'll be working to add support for configuring all of the Authenticated Origin Pull APIs through this provider.

There are three types of Authenticated Origin Pulls that can be enabled through the API, and these are the actions that one can take through it:

1. TLS Client Auth (Global Authenticated Origin Pulls):
* https://api.cloudflare.com/#zone-settings-change-tls-client-auth-setting

ex.
```hcl
resource "cloudflare_authenticated_origin_pulls" "foobar" {
  enabled = true
}
```

2. Per-Zone Authenticated Origin Pulls
* https://api.cloudflare.com/#zone-level-authenticated-origin-pulls-properties

ex.
```hcl
resource "cloudflare_per_zone_authenticated_origin_pulls_upload" "foo" {
  certificate = ""
  private_key = ""
}

resource "cloudflare_per_zone_authenticated_origin_pulls" "bar" {
  enabled = true
}
```

3. Per-Hostname Authenticated Origin Pulls
* https://api.cloudflare.com/#per-hostname-authenticated-origin-pull-properties

ex.
```hcl
resource "cloudflare_per_hostname_authenticated_origin_pulls_upload" "foo" {
  certificate = ""
  private_key = ""
}

resource "cloudflare_per_hostname_authenticated_origin_pulls" "bar" {
  hostname = "foobar.com"
  cert_id = cloudflare_per_hostname_authenticated_origin_pulls_upload.foo.id
  enabled = true
}
```

Tests will go in too!

**Comment by dhaynespls** [comment]
Would appreciate thoughts on the above resources, this is my first time working with a provider so basically taking a guess as to how it'll look. 

Specifically:
1) For the `certificate`, `private_key` fields in an ideal state one should be able to pull the cert / key from Vault. Does defining the resource as is allow for that? 
2) For Per Hostname's `cert_id` it needs to use the ID returned by the v4 API in upload, is that the method for how we would retrieve that ID from the upload resource? 

cc @jacobbednarz 🤠

**Comment by dhaynespls** [comment]
Borrowing from custom ssl we could take a strategy of:

```hcl
resource "cloudflare_per_zone_authenticated_origin_pulls" "foobar" {
  zone_id = ""
  per_zone_authenticated_origin_pulls_options = {
    certificate = "..."
    private_key = ""
    enabled = true
  }
```

and,

```hcl
resource "cloudflare_per_zone_authenticated_origin_pulls" "foobar" {
  zone_id = ""
  per_hostname_authenticated_origin_pulls_options = {
    certificate = ""
    private_key = ""
    hostname = "foobar.com"
    enabled = true
  }
```

This would allow for defining the zone id and bundles the two resources into one though I'm not sure if it addresses the questions posed above since it makes the operation in 2) a bit ambiguous

**Comment by wolfmd** [comment]
I think `cloudflare_per_<foo>_authenticated_origin_pulls_certificate` would probably be more clear than `cloudflare_per_<foo>_authenticated_origin_pulls_upload`. And the per_zone configuration enabled flag could be set on the zone resource https://www.terraform.io/docs/providers/cloudflare/r/zone.html though perhaps consistency of it always being a resource may be better.

**Comment by jacobbednarz** [comment]
Alrighty, there is a bit to unpack here but all should be solvable.

As for the resource itself, if we have multiple "layers" of entitlements (here a hostname, zone and account level) _and_ we can provide a schema that allows for all three with the [`Optional`](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#optional) and provide the logic within a method itself to build the correct one. Here is some pseudo-code to demonstrate (I've probably misunderstood AOP structure but bare with me 😛):

```go
func resourceCloudflareAccessApplication() *schema.Resource {
	return &schema.Resource{
		// .. snip

		Schema: map[string]*schema.Schema{
			"account_id": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"zone_id": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"hostname": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"options": {
				Type:     schema.TypeMap,
				Required: true,
			},

			// .. snip
		},
	},
}

func resourceCloudflareAccessApplicationCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*cloudflare.API)
	accountID := d.Get("account_id").(string)
	zoneID := d.Get("zone_id").(string)
	hostname := d.Get("hostname").(string)

	switch a {
	case accountID != "":
		// do account level API calls to build struct and send payload  
		UploadPerZoneAuthenticatedOriginPullsCertificate
	case zoneID != "":
		// do zone level API calls to build struct and send payload
		SetAuthenticatedOriginPullsStatus
	case hostname != "":
		// do hostname level API calls to build struct and send payload
		EditPerHostnameAuthenticatedOriginPullsConfig
	}
	default:
		return fmt.Errorf(`invalid option`, a)
	}

	return nil
}
```

Taking this approach allows you to maintain a single resource for all the configuration and share the attributes across all configurations that lend themselves to that. The alternative is duplicating all the schemas to be individual ones and I'm happy for you to make that choice on which makes more sense as I'm unfamiliar with AOP.

> For the `certificate`, `private_key` fields in an ideal state one should be able to pull the cert / key from Vault. Does defining the resource as is allow for that?

You mean Hashicorp Vault? If so, yes, you'd just need [configure/reference that provider setup](https://www.terraform.io/docs/providers/vault/index.html) elsewhere and pass the Cloudflare resource an ID. The schema itself is independent of how you provide it however we can make it `Sensitive` to avoid outputting it in the clear but it can still be stored that way if someone puts it in as a string and doesn't reference a backend like Vault. 

> For Per Hostname's `cert_id` it needs to use the ID returned by the v4 API in upload, is that the method for how we would retrieve that ID from the upload resource?

By the sounds of things (and depending on your approach), we would need to document that the hostname level one would require the two resources. This isn't a big deal and is how we do the [Filter based Firewall rules](https://www.terraform.io/docs/providers/cloudflare/r/firewall_rule.html#example-usage) due to the the call sequence works. It's actually two resources with separate API calls but the UI makes it seem like a single entity.

**Comment by dhaynespls** [comment]
That sounds like a solid plan! There is a sort of hierarchy with the feature depending on what combination of inputs are provided and tbh it makes using AOP a lot easier for the end user.
