### ISSUE TITLE
Request for Access Group datasource

### ISSUE THREAD

**Issue by dimko** [cloudflare/terraform-provider-cloudflare#754]
Add access_group datasource.

something like:

`data "cloudflare_access_group" "mygroup" {
  filter {
    name   = "fancy group name"
  }
}`

and be accessible as:

`data.cloudflare_access_group. mygroup.id`

Not sure how easy is  to fetch groups based on include, require or exclude parameters, but even filtering by name would be very useful.

### Affected Resource(s)
Please list the resources as a list, for example:
- access_group

**Comment by jacobbednarz** [comment]
Is there a reason why the resource can't be managed in Terraform and you get this with the existing resource?

**Comment by dimko** [comment]
Hi, Jacob. Yes. As I understand access groups are global resources, account wide. Access policies (and applications) are managed per zone in Cloudflare's side. In our case, we have several zones with slightly different configuration, but some similarities too. Each zone has its own state file.

Handling access group resources at zone level, in the same terraform instance and state (so their ids can be referenced in access policies -  cloudflare_access_group.group_name.id) causes error (resource already exists) every time a new access group needs to be added, since the access group was created as part of terraform apply for a different zone.

Referencing access group ids after fetching them through a data source would not require the creation of the resource and wouldn't throw errors in our case and would make them usable through different terraform implementations.

**Comment by estenrye** [comment]
Thumbs up on this issue.  This has been a thorn in my side for the better part of a year and @dimko just beat me to reporting it.

@dimko is absolutely right on the global (account wide) nature of the Cloudflare Access Groups.  In our environment we manage these in a separate terraform environment to manage these once, rather than in every environment we deploy.

This results in our current workflow:
- Make account wide changes in one terraform environment
- Add changes to a locals.tf file to share the id across multiple terraform environments
- Deploy to various environments.

This would drastically simplify my management of policies in terraform by eliminating the need for two pull requests.

**Comment by jacobbednarz** [comment]
> As I understand access groups are global resources, account wide. Access policies (and applications) are managed per zone in Cloudflare's side.

This is no longer the case; cloudflare/cloudflare-go#486 moves all the resources to an account wide endpoint and once pulled into the Terraform provider, will be handled transparently handled or require an update to your configuration files.

**Comment by dimko** [comment]
Great, since this is the case, I will close this one. Thank you

**Comment by sinamiandashti-fior** [comment]
I still dont understand!

We create the access group to use them in policies with group id 
How can we get ID of those groups later to assign to multi application policies since the groups are account level groups???

Please re-open this
withouth datasource make no sense
