### ISSUE TITLE
2.9 Breaking change - regular expressions on cloudflare_zones data source

### ISSUE THREAD

**Issue by tomaspinho** [cloudflare/terraform-provider-cloudflare#759]
### Terraform Version
Any

### Affected Resource(s)
- data_cloudflare_zones

### Terraform Configuration Files
```hcl
data "cloudflare_zones" "niceremote_com" {
  filter {
    name   = "domain.com"
    status = "active"
    paused = false
  }
}

was

data "cloudflare_zones" "niceremote_com" {
  filter {
    name   = "^domain.com$"
    status = "active"
    paused = false
  }
}
```

### Debug Output
NA

### Panic Output
NA
### Expected Behavior
Terraform runs to continue working.

### Actual Behavior
Terraform runs stopped working because regular expressions on "name" filters are no longer supported.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
The documentation recommends configuring the provider like so:
```hcl
provider "cloudflare" {
  version = "~> 2.0"
}
```
This will make Terraform auto upgrade to version 2.9 which uses the latest version of cloudflare-go. But this is actually a breaking change and should've been versioned and marked as such. Also, some migration documentation should've been written as I've had to contact Cloudflare's support (thought it was an API issue due to a bogus permissions error message instead) who managed to diagnose the problem.

### References
https://github.com/cloudflare/cloudflare-go/pull/478

**Comment by tomaspinho** [comment]
Let me know if there's anything I can do to help. We're heavy users of this provider and are willing to spend some time on it.

**Comment by jacobbednarz** [comment]
Thanks for raising the issue! I was initially confused as to what you were after here but if I understand it correctly, you're suggesting the change in question should have been a major release instead of minor?

Generally, major releases are ear marked for backwards incompatible changes where an alternative isn't available. Minor releases are for introducing changes in a compatible manner. Along with that, minor releases don't necessarily mean you can consistently update without making any changes to your implementation of a library. 

The functionality in question has changed how it is configured however you can still achieve the same outcome, just using a different incantation. We could have done a migration guide however we didn't. That's my fault as I opted to instead focused on [better examples in the documentation](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/data-sources/zones) to support the CHANGELOG and fix performance issues in the existing resource. 

I'm going to close off the issue now as there isn't anything outstanding to work on from the provider end however do let me know if you have any further questions or want to discuss further!

**Comment by tomaspinho** [comment]
No need to blame yourself 😀

Maybe I can help documenting this further as I'm sure other people will have the same problem in the future? Where should I start?

**Comment by jacobbednarz** [comment]
Sure thing. I'd start by asking what is currently missing and see if this was a one off or whether we need a different way of communicating changes. For example, was the CHANGELOG read and understood? Did it contain enough information to make the call on what is required? Is the data source website documentation sufficient?

I'm hesitant to introduce upgrade guides outside of major releases as the use cases are generally pretty varied and heavy content which cause many people's eyes to glaze over if done too often. I can be swayed though if we have a compelling reason.

**Comment by tomaspinho** [comment]
If people read the CHANGELOG (which I did not :sweat:), the information there may be sufficient. However, I've opened a PR here explaining the situation a bit further: https://github.com/cloudflare/terraform-provider-cloudflare/pull/760

**Comment by jacobbednarz** [comment]
Thanks, that bit of information is great context. Did you know the CHANGELOG existed? Would there have been a different place you would have expected these changes to appear?

As I previously mentioned, I'm interested into what lead up to this issue to provide clearer feedback earlier on.

**Comment by tomaspinho** [comment]
As I wrote in the PR review, I initially thought this was an API issue because of the bogus API permission error, which is not indicative of a potential problem with the provider. That's why I didn't initially check if there was any change in the provider.
