### ISSUE TITLE
New release coming soon?

### ISSUE THREAD

**Issue by marc-barry** [cloudflare/terraform-provider-cloudflare#829]
The latest release is https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v2.11.0. Since the release on September 10, 2020 there have been some significant updates to this provider which fixes how edge certificates and fallback origins are handled. I'm trying to avoid running our own release and thus wanted to know if a new release will be cut soon with all the updates.

**Comment by marc-barry** [comment]
I'll close this issue. We decided to run a fork to pick up the changes. I'll track when the next release occurs and move off the fork.

**Comment by jacobbednarz** [comment]
Releases are generally on a monthly-ish cadence or as needed depending on how much has changed. The latest unreleased is largely new features or documentation which is why there hasn't been a great deal of urgency; with the exception of what I assume you're tracking 😃 I'll take a look at a release later on today as we're coming up on that sweet spot anyway.

**Comment by jacobbednarz** [comment]
v2.12.0 was cut yesterday in case you missed it.
