### ISSUE TITLE
cloudflare_zone_settings_override.browser_cache_ttl default value marker reverts to specific value

### ISSUE THREAD

**Issue by viraptor** [cloudflare/terraform-provider-cloudflare#893]
### Terraform version

v0.13.4

### Affected resource(s)

cloudflare_zone_settings_override

### Terraform configuration files

```
resource "cloudflare_zone_settings_override" "resource_name" {
  zone_id = var.cloudflare_zone_id

  settings {
    ...
    browser_cache_ttl        = 0
    ...
}
```

### Expected behavior

After applying the changes with `browser_cache_ttl = 0`, the diff should return the no changes. (or using `0` should not be accepted when applying)

### Actual behavior

Diff returns a difference in
```
~ browser_cache_ttl           = 14400 -> 0
```

### Steps to reproduce

1. `terraform apply`
1. `terraform diff`

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by alex-feel** [comment]
It looks like I ran into an issue that is related to this issue in some way. I use Terraform Cloud v.0.14.3. After applying the `browser_cache_ttl = 0` option, I found that in the CloudFlare interface the Browser Cache TTL value remained at the default value, which is 4 hours. After that I tried to reproduce the issue several times, but I couldn't, I'm not sure what it could be, but the data in the interface was fresh (I was refreshing the page).

**Comment by jacobbednarz** [comment]
@viraptor Are you able to provide the `TF_LOG=DEBUG` output to accompany this change? We have a couple of tests that excercise this (annoying complex) code path which still seem to be passing so I wonder if there is something else happening here

https://github.com/cloudflare/terraform-provider-cloudflare/blob/999d2269765d2a8f40287e090f3526cc93569e27/cloudflare/resource_cloudflare_page_rule_test.go#L346-L361

**Comment by alex-feel** [comment]
> It looks like I ran into an issue that is related to this issue in some way. I use Terraform Cloud v.0.14.3. After applying the `browser_cache_ttl = 0` option, I found that in the CloudFlare interface the Browser Cache TTL value remained at the default value, which is 4 hours. After that I tried to reproduce the issue several times, but I couldn't, I'm not sure what it could be, but the data in the interface was fresh (I was refreshing the page).

I was able to reproduce the issue I mentioned above once again where browser_cache_ttl = 0 was not applied the first time. I created two zones at the same time, the first zone had a value of 0, the second did not, although it should have. On the second commit, when I didn't change anything in the configuration other than the location of the curly braces in the object (just wrapped it to another line), Terraform detected the changes and applied browser_cache_ttl = 0 to the second zone. Now I cannot repeat this again, but I can provide the configuration files and a log of applying changes. Should I create a new issue or is it worth posting all the information here?

**Comment by jacobbednarz** [comment]
@viraptor @simpsora are you folks still having this issue and able to share the reproduction steps/logs?

**Comment by viraptor** [comment]
Unfortunately not anymore. @alex-feel may be on to something with new zones. Once the current setting is at the explicit`14400`, reverting it to `0` doesn't show the same issue anymore.

**Comment by alex-feel** [comment]
@jacobbednarz I tried again and was able to reproduce the issue, if that helps I can post my config and the debug logs.

**Comment by jacobbednarz** [comment]
Yes please. The information needed can be found at `.github/ISSUE_TEMPLATE/bug_report.md`

**Comment by alex-feel** [comment]
So should I create a new issue or post the info here?

**Comment by jacobbednarz** [comment]
Here is fine if it is the same issue and we can reproduce it.

**Comment by alex-feel** [comment]
I believe this is the same issue, but if you think it is not, I can delete this post and create a new issue.

### Terraform version

Terraform Cloud 0.14.4

### Terraform configuration files

https://gist.github.com/alex-feel/1f23d869d9e6fe6d089203a4e4590504

### Debug output

After pushing the config above I got these plan and apply logs:
https://gist.github.com/alex-feel/68471dee9580f5251c711b54cb5688ab
https://gist.github.com/alex-feel/cd500f3a61d935ea33cfcef82ce29807

Here is the screenshots of what I was seeing in the CloudFlare account:
https://ibb.co/x6YMFpC
https://ibb.co/Nt6wXLM

Then I just added a comment to the config, here is a diff:
https://ibb.co/QcPsCFJ

After pushing the config with the comment I got these plan and apply logs:
https://gist.github.com/alex-feel/ac1a827a0ac7da3541626d568d298015
https://gist.github.com/alex-feel/545c9a0ae98b766554afc318e45ef99a

Here is the screenshots of what I was seeing in the CloudFlare account:
https://ibb.co/Hgshktj

### Expected behavior

browser_cache_ttl = 0 should have been applied to the testzone.com domain on first run.

### Actual behavior

browser_cache_ttl = 0 was applied to the testzone.com domain only on second run without changes.

### Steps to reproduce

Look at the Debug output.
