### ISSUE TITLE
defining cloudflare provider in required providers with cloudflare/cloudflare breaks the build

### ISSUE THREAD

**Issue by vital4ik** [cloudflare/terraform-provider-cloudflare#922]
invoking CF provider this way: 
`terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "2.17.0"
    }
    google = {
      source = "hashicorp/google"
      version = "3.52.0"
    }
  }
  required_version = "= 0.14.5"
}
provider "cloudflare" {
  api_token = var.global_apitoken //- replacing this part with hardcoded value has no effect so its not this variable
  }
`
Breaks the invocation with the following error:
`Error: credentials are not set correctly

  on <empty> line 0:
  (source code not available)`

### Terraform version
0.14.5

### Expected behavior
provider should initialize

### Actual behavior

error from above

### Important factoids

replacing cloudflare/cloudflare with terraform-providers/cloudflare fixes the issue allowing the module to run. no init required

**Comment by jacobbednarz** [comment]
Using your example above, I haven't been able to replicate using Terraform 0.14.5 and verison 2.17.0 of the provider. The fact that you're recieving an exception that the credentials are not set correctly hints that the provider works but it's not finding the credentials you're passing it for whatever reason. `terraform-providers/cloudflare` is not the correct provider (it's an artifact from before the move) and will not receive any updates since the split from the `terraform-provider` repository.

If you've upgraded Terraform versions, you should check out the [upgrade notes](https://www.terraform.io/upgrade-guides/) as each version has it's own requirements and may be impacting your ability to initialise.
