### ISSUE TITLE
Add Data Source for firewall_rule

### ISSUE THREAD

**Issue by ldb** [cloudflare/terraform-provider-cloudflare#997]
### Current Terraform version

Terraform v0.13.6

### Description

Add a Data Source to query existing firewall rules.

### Use cases

When adding new firewall rules it is necessary to know which rules already exist to provide the correct priority to new rules.

### Potential Terraform configuration

```hcl
data "cloudflare_firewall_rules" "example" {
  zone_id = "<ZONE_ID>"
  filter {
    priority = 5
    match = "gte"
    paused = false
  }
}
```

Attribute reference:
- `firewall_rules`

`firewall_rules`:
- `action`
- `priority`
- `paused`

**Comment by jacobbednarz** [comment]
Are you able to elaborate on your use case here a little more to help me understand? Are you only managing some of your firewall rules in Terraform? In other uses I've seen/used, this isn't required.

**Comment by ldb** [comment]
Our use case is building a module that packages some of Cloudflare's features together (firewall rules, rate limit, DNS records) and making this available to our teams. So, yes, not all rules are managed by the same team and we need to make sure the rules do not interfere with each other.

**Comment by jacobbednarz** [comment]
I don't think this is going to work the way you think it will because auto incrementing priority means you can't have any overrides in ordering for your rules. Imagine the scenario where you have team A with existing rules but team B needs to insert a rule in the middle of those rules (allow/bypass/etc) -- this won't be possible in your scenario without first manually reshuffling and spacing rules apart. See the documentation on ordering and priority at https://developers.cloudflare.com/firewall/cf-firewall-rules/order-priority for examples. 

The other issue you will face is that if different teams have the product resources split across multiple files and only apply their portion of the product changes, the others will be removed as Terraform will not have them in the current state file. 

Instead, I would recommend explicit ordering in shared files (or at least a way to apply all the product resources at once) to avoid the pitfalls outlined above.

**Comment by ldb** [comment]
The idea is that each team "owns" a block of n consecutive priorities. The overall order of the rules themselves is not that important, because each team will have an explicit condition for their own hostname in each of their filter expressions, which means only their own rules will ever match a request. However, we do not want any priority conflicts. Inside each "block" of rules, the order does matter, so we have to explicitly provide any (valid) priority.

```
1 - 1000 (reserved)
---
1001 - 1005 (team A)
---
1006 - 1010 (team B)
---
...
```

Technically, we could simply apply static priorities, so if we have x teams, there will be x rules with priority 1000, x rules with priority 1001 and so on. Since each rule matches only the traffic for their team, this should still work and any ties in the set of these matching rules would be resolved according to action precedence. However, that removes the possibility to have a bit more advanced orderings.

```
1 - 1000 (reserved)
---
1001 (team A)
1001 (team B)
---
1002 (team A)
1002 (team B)
---
...
```

**Comment by jacobbednarz** [comment]
> [...] this should still work and any ties in the set of these matching rules would be resolved according to action precedence

I'm afraid it doesn't work like this. If you've defined `priority` of a firewall rule, you can't have ties or duplication. Example:

```
curl -s \
  -H "X-Auth-Email: $CF_EMAIL" \
  -H "X-Auth-Key: $CF_API_KEY" \
  -H 'content-type: application/json' \
  https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/firewall/rules \
  -d '[{"action":"block", "filter":{"priority":5,"expression":"ip.addr ne 172.16.22.155","paused":false,"description":"Restrict access from these browsers on this address range.","ref":"FIL-100"}}]' 

{
  "result": [
    {
      "id": "3070f0b35d69470c916ac473f5fb9a8e",
      "paused": false,
      "action": "block",
      "filter": {
        "id": "1c31e087bf7946908c7bb757f4a2ea41",
        "expression": "ip.addr ne 172.16.22.155",
        "paused": false,
        "description": "Restrict access from these browsers on this address range.",
        "ref": "FIL-100"
      },
      "created_on": "2021-03-25T20:08:31Z",
      "modified_on": "2021-03-25T20:08:31Z",
      "index": 0
    }
  ],
  "success": true,
  "errors": [],
  "messages": []
}
```

```
curl -s \
  -H "X-Auth-Email: $CF_EMAIL" \
  -H "X-Auth-Key: $CF_API_KEY" \
  -H 'content-type: application/json' \
  https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/firewall/rules \
  -d '[{"action":"log", "filter":{"priority":5,"expression":"ip.addr ne 172.16.22.155","paused":false,"description":"Restrict access from these browsers on this address range.","ref":"FIL-100"}}]' 

{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10102,
      "message": "config duplicates an already existing config",
      "source": {
        "pointer": "/0"
      },
      "meta": {
        "id": "3070f0b35d69470c916ac473f5fb9a8e"
      }
    }
  ],
  "messages": null
}
```

(same applies if you change the rule expression itself but maintain the priority value)

Despite your comments above, I still don't see this working as you expect it to due to the potential pitfalls I mentioned I've however I've gone ahead and reviewed the PR for this. It's entirely up to you how you want to use this feature 😃

**Comment by ldb** [comment]
> If you've defined priority of a firewall rule, you can't have ties or duplication.

Interesting, the [documentation](https://developers.cloudflare.com/firewall/cf-firewall-rules/actions) suggests otherwise: "If the same request matches two different rules which have the same priority, precedence determines the action to take." In what case can those rules end up with the same priority then, if not set explicitly?

Either way, if this does not work, it's even more important to be able to avoid duplicate priorities.

Thank you for reviewing the PR, I will address the points.

**Comment by jacobbednarz** [comment]
closing this one as the PR has stalled
